global using Microsoft.Maui;
global using Microsoft.Maui.Graphics;
global using Microsoft.Maui.Hosting;
global using MauiControls = Microsoft.Maui.Controls;
global using BookReactor.Pages;
global using BookReactor.Models;
global using BookReactor.Services;
global using MauiReactor;
global using BookReactor.Resources.Styles;
global using MauiReactor.Animations;
global using MauiReactor.Canvas;
global using MauiReactor.Shapes;
